/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegioempresarial.aplicacionspinnerlist;

import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Gutierrez Muñoz; Maria Alejandro Escobar Castro
 * @grade 11C
 */
public class LoginWindow extends javax.swing.JFrame {
    UsersProvider usersProvider = new UsersProvider();
    VehiclesProvider vehiclesProvider = new VehiclesProvider();
    User loggedUser;
    boolean isAdmin = false;

    /**
     * Creates new form UserWindow
     */
    public LoginWindow() {
        initComponents();
    }
    
    public void setVehiclesProvider(VehiclesProvider vehiclesProvider){
        this.vehiclesProvider = vehiclesProvider;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        userIconButton = new javax.swing.JButton();
        iconsPanel = new javax.swing.JPanel();
        adminIconLabel = new javax.swing.JLabel();
        userIconLabel = new javax.swing.JLabel();
        adminIconButton = new javax.swing.JButton();
        roleLoginLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Ingresar");

        userIconButton.setText("<");
        userIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIconButtonActionPerformed(evt);
            }
        });

        iconsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adminIcon.png"))); // NOI18N
        iconsPanel.add(adminIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userIcon.png"))); // NOI18N
        iconsPanel.add(userIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        adminIconButton.setText(">");
        adminIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminIconButtonActionPerformed(evt);
            }
        });

        roleLoginLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        roleLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roleLoginLabel.setText("Ingresar como");

        usernameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usernameLabel.setText("Usuario:");

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordLabel.setText("Contraseña:");

        loginButton.setText("Ingresar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roleLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userIconButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminIconButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTextField)
                            .addComponent(passwordPasswordField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(titleLabel)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleLoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean login(){
        String username = usernameTextField.getText();
        char[] password = passwordPasswordField.getPassword();
        loggedUser = usersProvider.login(username, password);
        if(loggedUser != null){
            if(isAdmin){
                if(loggedUser.isAdmin()){
                    return true;
                }
            }else{
                if(!loggedUser.isAdmin()){
                return true;            
                }
            }
        }
        return false;
    }
    
    private void toggleUser (){
        isAdmin = !isAdmin;
        userIconButton.setEnabled(isAdmin);
        userIconLabel.setVisible(!isAdmin);
        adminIconLabel.setVisible(isAdmin);
        adminIconButton.setEnabled(!isAdmin);
        if(isAdmin){
            roleLoginLabel.setText("Ingresar como Administrador");
        }else{
            roleLoginLabel.setText("Ingresar como Usuario");
        }
    }
            
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        isAdmin = false;
        roleLoginLabel.setText("Ingresar como Usuario");
        userIconButton.setEnabled(false);
        userIconLabel.setVisible(true);
        adminIconLabel.setVisible(false);
        adminIconButton.setEnabled(true);
    }//GEN-LAST:event_formComponentShown

    private void adminIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminIconButtonActionPerformed
        toggleUser();
    }//GEN-LAST:event_adminIconButtonActionPerformed

    private void userIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIconButtonActionPerformed
        toggleUser();
    }//GEN-LAST:event_userIconButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        boolean isValidLogin = login();
        if(isValidLogin){
            UserWindow userWindow = new UserWindow();
            userWindow.setUsersProvider(usersProvider);
            userWindow.setVehiclesProvider(vehiclesProvider);
            userWindow.setLoggedUser(loggedUser);
            userWindow.setLocationRelativeTo(this);
            userWindow.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Credenciales Invalidas");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminIconButton;
    private javax.swing.JLabel adminIconLabel;
    private javax.swing.JPanel iconsPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JLabel roleLoginLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userIconButton;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
