/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegioempresarial.aplicacionspinnerlist;

import javax.swing.DefaultListModel;

/**
 *
 * @author Alejandro Gutierrez Muñoz; Maria Alejandro Escobar Castro
 * @grade 11C
 */
public class UserWindow extends javax.swing.JFrame {
    private DefaultListModel<String> vehicleListModel;
    UsersProvider usersProvider;
    VehiclesProvider vehiclesProvider;
    User loggedUser;

    /**
     * Creates new form Window
     */
    public UserWindow() {
        initComponents();
        vehicleListModel = new DefaultListModel<>();
        vehicleList.setModel(vehicleListModel);
    }
    
    public void setUsersProvider(UsersProvider usersProvider){
        this.usersProvider = usersProvider;
    }
    
    public void setVehiclesProvider(VehiclesProvider vehiclesProvider){
        this.vehiclesProvider = vehiclesProvider;
    }
    
    public void setLoggedUser(User loggedUser){
        this.loggedUser = loggedUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        listScrollPane = new javax.swing.JScrollPane();
        vehicleList = new javax.swing.JList<>();
        brandLabel = new javax.swing.JLabel();
        brandTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        horsepowerLabel = new javax.swing.JLabel();
        horsepowerSpinner = new javax.swing.JSpinner();
        valueLabel = new javax.swing.JLabel();
        valueSpinner = new javax.swing.JSpinner();
        sellButton = new javax.swing.JButton();
        goToUsersButton = new javax.swing.JButton();
        restoreDataButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Bienvenido, ");

        vehicleList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vehicleList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vehicleListValueChanged(evt);
            }
        });
        listScrollPane.setViewportView(vehicleList);

        brandLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        brandLabel.setText("Marca:");

        modelLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        modelLabel.setText("Modelo:");

        horsepowerLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        horsepowerLabel.setText("<html><p>Caballos de fuerza:</p></html>");

        horsepowerSpinner.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        horsepowerSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        valueLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        valueLabel.setText("Precio:");

        valueSpinner.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        valueSpinner.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 0.01f));

        sellButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sellButton.setText("Vender");

        goToUsersButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        goToUsersButton.setText("Ir a usuarios");

        restoreDataButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        restoreDataButton.setText("Reestablecer Valores");
        restoreDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreDataButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addButton.setText("Nuevo");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editButton.setText("Cambiar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(listScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sellButton)
                                .addGap(23, 23, 23)
                                .addComponent(goToUsersButton))
                            .addComponent(addButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandTextField)
                            .addComponent(modelTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(horsepowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horsepowerSpinner))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valueLabel)
                                .addGap(34, 34, 34)
                                .addComponent(valueSpinner))
                            .addComponent(restoreDataButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brandLabel)
                                    .addComponent(modelLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brandLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horsepowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horsepowerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valueLabel)
                            .addComponent(valueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(listScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellButton)
                    .addComponent(goToUsersButton)
                    .addComponent(restoreDataButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTitleName(String name){
        titleLabel.setText("Bienvenido, " + name);
    }
    
    public void refreshList(boolean isRemoved){
        int selectedIndex = vehicleList.getSelectedIndex();
        vehicleListModel.clear();
        for(Vehicle vehicle: vehiclesProvider.listVehicles()){
            vehicleListModel.addElement(vehicle.getBrand() + " " + vehicle.getModel());
        }
        if(isRemoved){
            vehicleList.setSelectedIndex(--selectedIndex);
        }else{
            vehicleList.setSelectedIndex(selectedIndex);
        }
    }
    
    public Vehicle getSelectedVehicle(){
        int selectedIndex = vehicleList.getSelectedIndex();
        if(selectedIndex == -1){
            return null;
        }
        return vehiclesProvider.listVehicles().get(selectedIndex);   
    }
    
    public Vehicle getSelectedVehicleNewValues(){
        return new Vehicle(getSelectedVehicle().getId(), (String) brandTextField.getText(), (String) modelTextField.getText(), (int) horsepowerSpinner.getValue(), (float) valueSpinner.getValue());
    }
    
    public boolean setSelectedVehicle(){
        boolean hasChanged = vehiclesProvider.setVehicleById(getSelectedVehicleNewValues());
        refreshList(false);
        return hasChanged;
    }
    
    public void deleteSelectedVehicle(){
        vehiclesProvider.removeVehicleById(getSelectedVehicle().getId());
        refreshList(true);
    }
    
    public void addVehicle(){
        vehiclesProvider.addVehicle(new Vehicle(0, "New Vehicle", "", 1, 1));
        refreshList(false);
    }
    
    public void listSetVehicleValues(Vehicle vehicle){
        if(vehicle != null){
            brandTextField.setText(vehicle.getBrand());
            modelTextField.setText(vehicle.getModel());
            horsepowerSpinner.setValue(vehicle.getHorsepower());
            valueSpinner.setValue(vehicle.getValue());
        }
    }
    
    public void resetVehicle(){
        listSetVehicleValues(getSelectedVehicle());
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setTitleName(loggedUser.getUserUsername());
        refreshList(false);
    }//GEN-LAST:event_formComponentShown

    private void restoreDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreDataButtonActionPerformed
        resetVehicle();
    }//GEN-LAST:event_restoreDataButtonActionPerformed

    private void vehicleListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vehicleListValueChanged
        resetVehicle();
    }//GEN-LAST:event_vehicleListValueChanged

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteSelectedVehicle();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        setSelectedVehicle();
    }//GEN-LAST:event_editButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addVehicle();
    }//GEN-LAST:event_addButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JTextField brandTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton goToUsersButton;
    private javax.swing.JLabel horsepowerLabel;
    private javax.swing.JSpinner horsepowerSpinner;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JButton restoreDataButton;
    private javax.swing.JButton sellButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JSpinner valueSpinner;
    private javax.swing.JList<String> vehicleList;
    // End of variables declaration//GEN-END:variables
}
